# Build stage
FROM alpine:3.22

RUN apk --no-cache add ca-certificates && adduser -D -u 65532 an

WORKDIR /app/

# The binary is copied by GoReleaser
COPY an /app/

USER an

ENV PORT=8080
EXPOSE $PORT

# Health check
HEALTHCHECK --interval=30s --timeout=3s \
  CMD wget --no-verbose --tries=1 --spider http://localhost:${PORT}/health || exit 1

ENTRYPOINT ["/app/an"]
